---
application:
  name: ecommerce-mern-app
  type: nodejs
  root: public_html  
  node_version: '14'

build:
  commands:
    - cd server
    - npm install
    - npm run build
    - cd ./client/client
    - npm install
    - npm run build

deploy:
  commands:
    - cd server
    - npm run dev
    - cd ./client/client
    - npm start

env:
  NODE_ENV: production
  API_URL: https://api.forlandliving.com
