---
application:
  name: Ecommerce-Mern-App
  type: nodejs
  root: server
  node_version: '14'

build:
  commands:
    - cd ./client/client
    - npm install
    - npm run build

deploy:
  commands:
    - cd server
    - npm install
    - npm run dev
    
env:
  NODE_ENV: production
  API_URL: https://api.forlandliving.com
