---
deployment:
  tasks: 
   - export DEPLOYPATH=/home/user/public_html/
   - /bin/cp index.html $DEPLOYPATH
   - /bin/cp styl

application:
  name: ecommerce-app
  type: nodejs
  root: public_html  
  node_version: '14'

build:
  commands:
    - cd backend
    - npm install
    - npm run build
    - cd ../frontend
    - npm install
    - npm run build

deploy:
  commands:
    - cd backend
    - npm start
    - cd ../frontend
    - npm start

env:
  NODE_ENV: production
  API_URL: https://api.forlandliving.com
